#include <stdio.h>
#include <windows.h>
#include <stdlib.h>
#include<string.h>

void gotoxy(int x,int y)
{
	HANDLE app;
	COORD  pos;
	pos.X=x;
	pos.Y=y;
	app=GetStdHandle(STD_OUTPUT_HANDLE);
	SetConsoleCursorPosition(app,pos);
}

void dot_num(char s[])
{
	int i=0,j=0,jj=0,len=0;
	len=strlen(s);
	for(int k=0,int t=0;k<len;k++,t++)
	{
		if(k!=0&&t!=7&&t%8==0){i=0;jj++;};
		switch(s[k])
		{
		case '0':j=jj*8;
			gotoxy(i,j++);printf("            ");
			gotoxy(i,j++);printf("    ¡ö¡ö¡ö  ");
			gotoxy(i,j++);printf("  ¡ö      ¡ö");
			gotoxy(i,j++);printf("  ¡ö¡ö    ¡ö");
			gotoxy(i,j++);printf("  ¡ö  ¡ö  ¡ö");
			gotoxy(i,j++);printf("  ¡ö    ¡ö¡ö");
			gotoxy(i,j++);printf("  ¡ö      ¡ö");
			gotoxy(i,j++);printf("    ¡ö¡ö¡ö  ");
			i+=12;break;
		case '1':j=jj*8;
			gotoxy(i,j++);printf("            ");
			gotoxy(i,j++);printf("      ¡ö    ");
			gotoxy(i,j++);printf("    ¡ö¡ö    ");
			gotoxy(i,j++);printf("      ¡ö    ");
			gotoxy(i,j++);printf("      ¡ö    ");
			gotoxy(i,j++);printf("      ¡ö    ");
			gotoxy(i,j++);printf("      ¡ö    ");
			gotoxy(i,j++);printf("  ¡ö¡ö¡ö¡ö¡ö");
			i+=12;break;
		case '2':j=jj*8;
			gotoxy(i,j++);printf("            ");
			gotoxy(i,j++);printf("  ¡ö¡ö¡ö¡ö¡ö");
			gotoxy(i,j++);printf("          ¡ö");
			gotoxy(i,j++);printf("          ¡ö");
			gotoxy(i,j++);printf("  ¡ö¡ö¡ö¡ö¡ö");
			gotoxy(i,j++);printf("  ¡ö        ");
			gotoxy(i,j++);printf("  ¡ö        ");
			gotoxy(i,j++);printf("  ¡ö¡ö¡ö¡ö¡ö");
			i+=12;break;
		case '3':j=jj*8;
			gotoxy(i,j++);printf("            ");
			gotoxy(i,j++);printf("  ¡ö¡ö¡ö¡ö¡ö");
			gotoxy(i,j++);printf("          ¡ö");
			gotoxy(i,j++);printf("          ¡ö");
			gotoxy(i,j++);printf("  ¡ö¡ö¡ö¡ö¡ö");
			gotoxy(i,j++);printf("          ¡ö");
			gotoxy(i,j++);printf("          ¡ö");
			gotoxy(i,j++);printf("  ¡ö¡ö¡ö¡ö¡ö");
			i+=12;break;
		case '4':j=jj*8;
			gotoxy(i,j++);printf("            ");
			gotoxy(i,j++);printf("  ¡ö      ¡ö");
			gotoxy(i,j++);printf("  ¡ö      ¡ö");
			gotoxy(i,j++);printf("  ¡ö      ¡ö");
			gotoxy(i,j++);printf("  ¡ö¡ö¡ö¡ö¡ö");
			gotoxy(i,j++);printf("          ¡ö");
			gotoxy(i,j++);printf("          ¡ö");
			gotoxy(i,j++);printf("          ¡ö");
			i+=12;break;
		case '5':j=jj*8;
			gotoxy(i,j++);printf("            ");
			gotoxy(i,j++);printf("  ¡ö¡ö¡ö¡ö¡ö");
			gotoxy(i,j++);printf("  ¡ö        ");
			gotoxy(i,j++);printf("  ¡ö        ");
			gotoxy(i,j++);printf("  ¡ö¡ö¡ö¡ö¡ö");
			gotoxy(i,j++);printf("          ¡ö");
			gotoxy(i,j++);printf("          ¡ö");
			gotoxy(i,j++);printf("  ¡ö¡ö¡ö¡ö¡ö");
			i+=12;break;
		case '6':j=jj*8;
			gotoxy(i,j++);printf("            ");
			gotoxy(i,j++);printf("  ¡ö¡ö¡ö¡ö¡ö");
			gotoxy(i,j++);printf("  ¡ö        ");
			gotoxy(i,j++);printf("  ¡ö        ");
			gotoxy(i,j++);printf("  ¡ö¡ö¡ö¡ö¡ö");
			gotoxy(i,j++);printf("  ¡ö      ¡ö");
			gotoxy(i,j++);printf("  ¡ö      ¡ö");
			gotoxy(i,j++);printf("  ¡ö¡ö¡ö¡ö¡ö");
			i+=12;break;
		case '7':j=jj*8;
			gotoxy(i,j++);printf("            ");
			gotoxy(i,j++);printf("  ¡ö¡ö¡ö¡ö¡ö");
			gotoxy(i,j++);printf("          ¡ö");
			gotoxy(i,j++);printf("          ¡ö");
			gotoxy(i,j++);printf("          ¡ö");
			gotoxy(i,j++);printf("          ¡ö");
			gotoxy(i,j++);printf("          ¡ö");
			gotoxy(i,j++);printf("          ¡ö");
			i+=12;break;
		case '8':j=jj*8;
			gotoxy(i,j++);printf("            ");
			gotoxy(i,j++);printf("  ¡ö¡ö¡ö¡ö¡ö");
			gotoxy(i,j++);printf("  ¡ö      ¡ö");
			gotoxy(i,j++);printf("  ¡ö      ¡ö");
			gotoxy(i,j++);printf("  ¡ö¡ö¡ö¡ö¡ö");
			gotoxy(i,j++);printf("  ¡ö      ¡ö");
			gotoxy(i,j++);printf("  ¡ö      ¡ö");
			gotoxy(i,j++);printf("  ¡ö¡ö¡ö¡ö¡ö");
			i+=12;break;
		case '9':j=jj*8;
			gotoxy(i,j++);printf("            ");
			gotoxy(i,j++);printf("  ¡ö¡ö¡ö¡ö¡ö");
			gotoxy(i,j++);printf("  ¡ö      ¡ö");
			gotoxy(i,j++);printf("  ¡ö      ¡ö");
			gotoxy(i,j++);printf("  ¡ö¡ö¡ö¡ö¡ö");
			gotoxy(i,j++);printf("          ¡ö");
			gotoxy(i,j++);printf("          ¡ö");
			gotoxy(i,j++);printf("  ¡ö¡ö¡ö¡ö¡ö");
			i+=12;break;
		}
	}
}

void dot(char s[])
{
	int i=0,j=0,jj=0,len=0;
	len=strlen(s);
	for(int k=0,int t=0;k<len;k++,t++)
	{
		if(k!=0&&t!=7&&t%8==0){i=0;jj++;};
		switch(s[k])
		{
	case '0':j=jj*8;
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("    ¡ö¡ö¡ö  ");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("  ¡ö¡ö    ¡ö");
		gotoxy(i,j++);printf("  ¡ö  ¡ö  ¡ö");
		gotoxy(i,j++);printf("  ¡ö    ¡ö¡ö");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("    ¡ö¡ö¡ö  ");
		i+=12;break;
	case '1':j=jj*8;
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("      ¡ö    ");
		gotoxy(i,j++);printf("    ¡ö¡ö    ");
		gotoxy(i,j++);printf("      ¡ö    ");
		gotoxy(i,j++);printf("      ¡ö    ");
		gotoxy(i,j++);printf("      ¡ö    ");
		gotoxy(i,j++);printf("      ¡ö    ");
		gotoxy(i,j++);printf("  ¡ö¡ö¡ö¡ö¡ö");
		i+=12;break;
	case '2':j=jj*8;
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("  ¡ö¡ö¡ö¡ö¡ö");
		gotoxy(i,j++);printf("          ¡ö");
		gotoxy(i,j++);printf("          ¡ö");
		gotoxy(i,j++);printf("  ¡ö¡ö¡ö¡ö¡ö");
		gotoxy(i,j++);printf("  ¡ö        ");
		gotoxy(i,j++);printf("  ¡ö        ");
		gotoxy(i,j++);printf("  ¡ö¡ö¡ö¡ö¡ö");
		i+=12;break;
	case '3':j=jj*8;
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("  ¡ö¡ö¡ö¡ö¡ö");
		gotoxy(i,j++);printf("          ¡ö");
		gotoxy(i,j++);printf("          ¡ö");
		gotoxy(i,j++);printf("  ¡ö¡ö¡ö¡ö¡ö");
		gotoxy(i,j++);printf("          ¡ö");
		gotoxy(i,j++);printf("          ¡ö");
		gotoxy(i,j++);printf("  ¡ö¡ö¡ö¡ö¡ö");
		i+=12;break;
	case '4':j=jj*8;
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("  ¡ö¡ö¡ö¡ö¡ö");
		gotoxy(i,j++);printf("          ¡ö");
		gotoxy(i,j++);printf("          ¡ö");
		gotoxy(i,j++);printf("          ¡ö");
		i+=12;break;
	case '5':j=jj*8;
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("  ¡ö¡ö¡ö¡ö¡ö");
		gotoxy(i,j++);printf("  ¡ö        ");
		gotoxy(i,j++);printf("  ¡ö        ");
		gotoxy(i,j++);printf("  ¡ö¡ö¡ö¡ö¡ö");
		gotoxy(i,j++);printf("          ¡ö");
		gotoxy(i,j++);printf("          ¡ö");
		gotoxy(i,j++);printf("  ¡ö¡ö¡ö¡ö¡ö");
		i+=12;break;
	case '6':j=jj*8;
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("  ¡ö¡ö¡ö¡ö¡ö");
		gotoxy(i,j++);printf("  ¡ö        ");
		gotoxy(i,j++);printf("  ¡ö        ");
		gotoxy(i,j++);printf("  ¡ö¡ö¡ö¡ö¡ö");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("  ¡ö¡ö¡ö¡ö¡ö");
		i+=12;break;
	case '7':j=jj*8;
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("  ¡ö¡ö¡ö¡ö¡ö");
		gotoxy(i,j++);printf("          ¡ö");
		gotoxy(i,j++);printf("          ¡ö");
		gotoxy(i,j++);printf("          ¡ö");
		gotoxy(i,j++);printf("          ¡ö");
		gotoxy(i,j++);printf("          ¡ö");
		gotoxy(i,j++);printf("          ¡ö");
		i+=12;break;
	case '8':j=jj*8;
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("  ¡ö¡ö¡ö¡ö¡ö");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("  ¡ö¡ö¡ö¡ö¡ö");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("  ¡ö¡ö¡ö¡ö¡ö");
		i+=12;break;
	case '9':j=jj*8;
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("  ¡ö¡ö¡ö¡ö¡ö");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("  ¡ö¡ö¡ö¡ö¡ö");
		gotoxy(i,j++);printf("          ¡ö");
		gotoxy(i,j++);printf("          ¡ö");
		gotoxy(i,j++);printf("  ¡ö¡ö¡ö¡ö¡ö");
		i+=12;break;
	case 'A':j=jj*8;
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("      ¡ö    ");
		gotoxy(i,j++);printf("    ¡ö  ¡ö  ");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("  ¡ö¡ö¡ö¡ö¡ö");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		i+=12;break;
	case 'B':j=jj*8;
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("  ¡ö¡ö¡ö¡ö  ");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("  ¡ö¡ö¡ö¡ö  ");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("  ¡ö¡ö¡ö¡ö  ");
		i+=12;break;
	case 'C':j=jj*8;
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("    ¡ö¡ö¡ö  ");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("  ¡ö        ");
		gotoxy(i,j++);printf("  ¡ö        ");
		gotoxy(i,j++);printf("  ¡ö        ");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("    ¡ö¡ö¡ö  ");
		i+=12;break;
	case 'D':j=jj*8;
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("  ¡ö¡ö¡ö¡ö  ");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("  ¡ö¡ö¡ö¡ö  ");
		i+=12;break;
	case 'E':j=jj*8;
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("  ¡ö¡ö¡ö¡ö¡ö");
		gotoxy(i,j++);printf("  ¡ö        ");
		gotoxy(i,j++);printf("  ¡ö        ");
		gotoxy(i,j++);printf("  ¡ö¡ö¡ö¡ö¡ö");
		gotoxy(i,j++);printf("  ¡ö        ");
		gotoxy(i,j++);printf("  ¡ö        ");
		gotoxy(i,j++);printf("  ¡ö¡ö¡ö¡ö¡ö");
		i+=12;break;
	case 'F':j=jj*8;
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("  ¡ö¡ö¡ö¡ö¡ö");
		gotoxy(i,j++);printf("  ¡ö        ");
		gotoxy(i,j++);printf("  ¡ö        ");
		gotoxy(i,j++);printf("  ¡ö¡ö¡ö¡ö  ");
		gotoxy(i,j++);printf("  ¡ö        ");
		gotoxy(i,j++);printf("  ¡ö        ");
		gotoxy(i,j++);printf("  ¡ö        ");
		i+=12;break;
	case 'G':j=jj*8;
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("    ¡ö¡ö¡ö  ");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("  ¡ö        ");
		gotoxy(i,j++);printf("  ¡ö        ");
		gotoxy(i,j++);printf("  ¡ö    ¡ö¡ö");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("    ¡ö¡ö¡ö  ");
		i+=12;break;
	case 'H':j=jj*8;
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("  ¡ö¡ö¡ö¡ö¡ö");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		i+=12;break;
	case 'I':j=jj*8;
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("    ¡ö¡ö¡ö  ");
		gotoxy(i,j++);printf("      ¡ö    ");
		gotoxy(i,j++);printf("      ¡ö    ");
		gotoxy(i,j++);printf("      ¡ö    ");
		gotoxy(i,j++);printf("      ¡ö    ");
		gotoxy(i,j++);printf("      ¡ö    ");
		gotoxy(i,j++);printf("    ¡ö¡ö¡ö  ");
		i+=12;break;
	case 'J':j=jj*8;
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("  ¡ö¡ö¡ö¡ö¡ö");
		gotoxy(i,j++);printf("      ¡ö    ");
		gotoxy(i,j++);printf("      ¡ö    ");
		gotoxy(i,j++);printf("      ¡ö    ");
		gotoxy(i,j++);printf("      ¡ö    ");
		gotoxy(i,j++);printf("  ¡ö  ¡ö    ");
		gotoxy(i,j++);printf("    ¡ö¡ö    ");
		i+=12;break;
	case 'K':j=jj*8;
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("  ¡ö    ¡ö  ");
		gotoxy(i,j++);printf("  ¡ö  ¡ö    ");
		gotoxy(i,j++);printf("  ¡ö¡ö      ");
		gotoxy(i,j++);printf("  ¡ö  ¡ö    ");
		gotoxy(i,j++);printf("  ¡ö    ¡ö  ");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		i+=12;break;
	case 'L':j=jj*8;
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("  ¡ö        ");
		gotoxy(i,j++);printf("  ¡ö        ");
		gotoxy(i,j++);printf("  ¡ö        ");
		gotoxy(i,j++);printf("  ¡ö        ");
		gotoxy(i,j++);printf("  ¡ö        ");
		gotoxy(i,j++);printf("  ¡ö        ");
		gotoxy(i,j++);printf("  ¡ö¡ö¡ö¡ö¡ö");
		i+=12;break;
	case 'M':j=jj*8;
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("  ¡ö¡ö  ¡ö¡ö");
		gotoxy(i,j++);printf("  ¡ö  ¡ö  ¡ö");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		i+=12;break;
	case 'N':j=jj*8;
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("  ¡ö¡ö    ¡ö");
		gotoxy(i,j++);printf("  ¡ö  ¡ö  ¡ö");
		gotoxy(i,j++);printf("  ¡ö    ¡ö¡ö");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		i+=12;break;
	case 'O':j=jj*8;
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("    ¡ö¡ö¡ö  ");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("    ¡ö¡ö¡ö  ");
		i+=12;break;
	case 'P':j=jj*8;
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("  ¡ö¡ö¡ö¡ö  ");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("  ¡ö¡ö¡ö¡ö  ");
		gotoxy(i,j++);printf("  ¡ö        ");
		gotoxy(i,j++);printf("  ¡ö        ");
		gotoxy(i,j++);printf("  ¡ö        ");
		i+=12;break;
	case 'Q':j=jj*8;
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("    ¡ö¡ö¡ö  ");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("  ¡ö  ¡ö  ¡ö");
		gotoxy(i,j++);printf("  ¡ö    ¡ö¡ö");
		gotoxy(i,j++);printf("    ¡ö¡ö¡ö¡ö");
		i+=12;break;
	case 'R':j=jj*8;
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("  ¡ö¡ö¡ö¡ö  ");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("  ¡ö¡ö¡ö¡ö  ");
		gotoxy(i,j++);printf("  ¡ö  ¡ö    ");
		gotoxy(i,j++);printf("  ¡ö    ¡ö  ");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		i+=12;break;
	case 'S':j=jj*8;
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("    ¡ö¡ö¡ö  ");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("  ¡ö        ");
		gotoxy(i,j++);printf("  ¡ö¡ö¡ö¡ö  ");
		gotoxy(i,j++);printf("          ¡ö");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("    ¡ö¡ö¡ö  ");
		i+=12;break;
	case 'T':j=jj*8;
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("  ¡ö¡ö¡ö¡ö¡ö");
		gotoxy(i,j++);printf("      ¡ö    ");
		gotoxy(i,j++);printf("      ¡ö    ");
		gotoxy(i,j++);printf("      ¡ö    ");
		gotoxy(i,j++);printf("      ¡ö    ");
		gotoxy(i,j++);printf("      ¡ö    ");
		gotoxy(i,j++);printf("      ¡ö    ");
		i+=12;break;
	case 'U':j=jj*8;
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("    ¡ö¡ö¡ö  ");
		i+=12;break;
	case 'V':j=jj*8;
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("    ¡ö  ¡ö  ");
		gotoxy(i,j++);printf("      ¡ö    ");
		i+=12;break;
	case 'W':j=jj*8;
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("  ¡ö  ¡ö  ¡ö");
		gotoxy(i,j++);printf("  ¡ö  ¡ö  ¡ö");
		gotoxy(i,j++);printf("  ¡ö  ¡ö  ¡ö");
		gotoxy(i,j++);printf("    ¡ö  ¡ö  ");
		gotoxy(i,j++);printf("    ¡ö  ¡ö  ");
		i+=12;break;
	case 'X':j=jj*8;
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("    ¡ö  ¡ö  ");
		gotoxy(i,j++);printf("      ¡ö    ");
		gotoxy(i,j++);printf("    ¡ö  ¡ö  ");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		i+=12;break;
	case 'Y':j=jj*8;
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("    ¡ö  ¡ö  ");
		gotoxy(i,j++);printf("      ¡ö    ");
		gotoxy(i,j++);printf("      ¡ö    ");
		gotoxy(i,j++);printf("      ¡ö    ");
		gotoxy(i,j++);printf("      ¡ö    ");
		i+=12;break;
	case 'Z':j=jj*8;
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("  ¡ö¡ö¡ö¡ö¡ö");
		gotoxy(i,j++);printf("          ¡ö");
		gotoxy(i,j++);printf("        ¡ö  ");
		gotoxy(i,j++);printf("      ¡ö    ");
		gotoxy(i,j++);printf("    ¡ö      ");
		gotoxy(i,j++);printf("  ¡ö        ");
		gotoxy(i,j++);printf("  ¡ö¡ö¡ö¡ö¡ö");
		i+=12;break;
	case 'a':j=jj*8;
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("    ¡ö¡ö    ");
		gotoxy(i,j++);printf("  ¡ö    ¡ö  ");
		gotoxy(i,j++);printf("  ¡ö    ¡ö  ");
		gotoxy(i,j++);printf("  ¡ö    ¡ö  ");
		gotoxy(i,j++);printf("    ¡ö¡ö  ¡ö");
		i+=12;break;
	case 'b':j=jj*8;
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("  ¡ö        ");
		gotoxy(i,j++);printf("  ¡ö        ");
		gotoxy(i,j++);printf("  ¡ö        ");
		gotoxy(i,j++);printf("  ¡ö¡ö¡ö    ");
		gotoxy(i,j++);printf("  ¡ö    ¡ö  ");
		gotoxy(i,j++);printf("  ¡ö    ¡ö  ");
		gotoxy(i,j++);printf("  ¡ö¡ö¡ö    ");
		i+=12;break;
	case 'c':j=jj*8;
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("    ¡ö¡ö¡ö  ");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("  ¡ö        ");
		gotoxy(i,j++);printf("  ¡ö      ¡ö");
		gotoxy(i,j++);printf("    ¡ö¡ö¡ö  ");
		i+=12;break;
	case 'd':j=jj*8;
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("        ¡ö  ");
		gotoxy(i,j++);printf("        ¡ö  ");
		gotoxy(i,j++);printf("        ¡ö  ");
		gotoxy(i,j++);printf("    ¡ö¡ö¡ö  ");
		gotoxy(i,j++);printf("  ¡ö    ¡ö  ");
		gotoxy(i,j++);printf("  ¡ö    ¡ö  ");
		gotoxy(i,j++);printf("    ¡ö¡ö¡ö  ");
		i+=12;break;
	case 'e':j=jj*8;
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("    ¡ö¡ö    ");
		gotoxy(i,j++);printf("  ¡ö    ¡ö  ");
		gotoxy(i,j++);printf("  ¡ö¡ö¡ö¡ö  ");
		gotoxy(i,j++);printf("  ¡ö        ");
		gotoxy(i,j++);printf("    ¡ö¡ö¡ö  ");
		i+=12;break;
	case 'f':j=jj*8;
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("      ¡ö¡ö  ");
		gotoxy(i,j++);printf("      ¡ö    ");
		gotoxy(i,j++);printf("    ¡ö¡ö¡ö  ");
		gotoxy(i,j++);printf("      ¡ö    ");
		gotoxy(i,j++);printf("      ¡ö    ");
		gotoxy(i,j++);printf("      ¡ö    ");
		i+=12;break;
	case 'g':j=jj*8;
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("    ¡ö¡ö    ");
		gotoxy(i,j++);printf("  ¡ö    ¡ö  ");
		gotoxy(i,j++);printf("  ¡ö¡ö¡ö¡ö  ");
		gotoxy(i,j++);printf("        ¡ö  ");
		gotoxy(i,j++);printf("  ¡ö    ¡ö  ");
		gotoxy(i,j++);printf("    ¡ö¡ö    ");
		i+=12;break;
	case 'h':j=jj*8;
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("  ¡ö        ");
		gotoxy(i,j++);printf("  ¡ö        ");
		gotoxy(i,j++);printf("  ¡ö¡ö¡ö    ");
		gotoxy(i,j++);printf("  ¡ö    ¡ö  ");
		gotoxy(i,j++);printf("  ¡ö    ¡ö  ");
		gotoxy(i,j++);printf("  ¡ö    ¡ö  ");
		i+=12;break;
	case 'i':j=jj*8;
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("      ¡ö    ");
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("      ¡ö    ");
		gotoxy(i,j++);printf("      ¡ö    ");
		gotoxy(i,j++);printf("      ¡ö    ");
		gotoxy(i,j++);printf("      ¡ö    ");
		i+=12;break;
	case 'j':j=jj*8;
		gotoxy(i,j++);printf("            ");
		
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("        ¡ö  ");
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("        ¡ö  ");
		gotoxy(i,j++);printf("        ¡ö  ");
		gotoxy(i,j++);printf("    ¡ö  ¡ö  ");
		gotoxy(i,j++);printf("      ¡ö¡ö  ");
		i+=12;break;
	case 'k':j=jj*8;
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("  ¡ö    ¡ö  ");
		gotoxy(i,j++);printf("  ¡ö  ¡ö    ");
		gotoxy(i,j++);printf("  ¡ö¡ö      ");
		gotoxy(i,j++);printf("  ¡ö  ¡ö    ");
		gotoxy(i,j++);printf("  ¡ö    ¡ö  ");
		i+=12;break;
	case 'l':j=jj*8;
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("    ¡ö      ");
		gotoxy(i,j++);printf("    ¡ö      ");
		gotoxy(i,j++);printf("    ¡ö      ");
		gotoxy(i,j++);printf("    ¡ö      ");
		gotoxy(i,j++);printf("    ¡ö  ¡ö  ");
		gotoxy(i,j++);printf("    ¡ö¡ö¡ö  ");
		i+=12;break;
	case 'm':j=jj*8;
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("    ¡ö  ¡ö  ");
		gotoxy(i,j++);printf("  ¡ö  ¡ö  ¡ö");
		gotoxy(i,j++);printf("  ¡ö  ¡ö  ¡ö");
		i+=12;break;
	case 'n':j=jj*8;
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("  ¡ö¡ö¡ö    ");
		gotoxy(i,j++);printf("  ¡ö    ¡ö  ");
		gotoxy(i,j++);printf("  ¡ö    ¡ö  ");
		gotoxy(i,j++);printf("  ¡ö    ¡ö  ");
		i+=12;break;
	case 'o':j=jj*8;
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("    ¡ö¡ö    ");
		gotoxy(i,j++);printf("  ¡ö    ¡ö  ");
		gotoxy(i,j++);printf("  ¡ö    ¡ö  ");
		gotoxy(i,j++);printf("    ¡ö¡ö    ");
		i+=12;break;
	case 'p':j=jj*8;
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("    ¡ö¡ö    ");
		gotoxy(i,j++);printf("  ¡ö    ¡ö  ");
		gotoxy(i,j++);printf("  ¡ö    ¡ö  ");
		gotoxy(i,j++);printf("  ¡ö¡ö¡ö    ");
		gotoxy(i,j++);printf("  ¡ö        ");
		gotoxy(i,j++);printf("  ¡ö        ");
		i+=12;break;
	case 'q':j=jj*8;
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("    ¡ö¡ö    ");
		gotoxy(i,j++);printf("  ¡ö    ¡ö  ");
		gotoxy(i,j++);printf("  ¡ö    ¡ö  ");
		gotoxy(i,j++);printf("    ¡ö¡ö¡ö  ");
		gotoxy(i,j++);printf("        ¡ö  ");
		gotoxy(i,j++);printf("        ¡ö  ");
		i+=12;break;
	case 'r':j=jj*8;
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("    ¡ö  ¡ö  ");
		gotoxy(i,j++);printf("    ¡ö¡ö    ");
		gotoxy(i,j++);printf("    ¡ö      ");
		gotoxy(i,j++);printf("    ¡ö      ");
		i+=12;break;
	case 's':j=jj*8;
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("    ¡ö¡ö¡ö  ");
		gotoxy(i,j++);printf("  ¡ö        ");
		gotoxy(i,j++);printf("  ¡ö¡ö¡ö¡ö  ");
		gotoxy(i,j++);printf("        ¡ö  ");
		gotoxy(i,j++);printf("  ¡ö¡ö¡ö    ");
		i+=12;break;
	case 't':j=jj*8;
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("      ¡ö    ");
		gotoxy(i,j++);printf("    ¡ö¡ö¡ö  ");
		gotoxy(i,j++);printf("      ¡ö    ");
		gotoxy(i,j++);printf("      ¡ö    ");
		gotoxy(i,j++);printf("      ¡ö¡ö  ");
		i+=12;break;
	case 'u':j=jj*8;
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("  ¡ö    ¡ö  ");
		gotoxy(i,j++);printf("  ¡ö    ¡ö  ");
		gotoxy(i,j++);printf("  ¡ö    ¡ö  ");
		gotoxy(i,j++);printf("    ¡ö¡ö    ");
		i+=12;break;
	case 'v':j=jj*8;
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("    ¡ö  ¡ö  ");
		gotoxy(i,j++);printf("    ¡ö  ¡ö  ");
		gotoxy(i,j++);printf("      ¡ö    ");
		i+=12;break;
	case 'w':j=jj*8;
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("  ¡ö  ¡ö  ¡ö");
		gotoxy(i,j++);printf("  ¡ö  ¡ö  ¡ö");
		gotoxy(i,j++);printf("    ¡ö  ¡ö  ");
		i+=12;break;
	case 'x':j=jj*8;
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("    ¡ö  ¡ö  ");
		gotoxy(i,j++);printf("      ¡ö    ");
		gotoxy(i,j++);printf("    ¡ö  ¡ö  ");
		i+=12;break;
	case 'y':j=jj*8;
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("    ¡ö  ¡ö  ");
		gotoxy(i,j++);printf("    ¡ö  ¡ö  ");
		gotoxy(i,j++);printf("      ¡ö    ");
		gotoxy(i,j++);printf("    ¡ö      ");
		gotoxy(i,j++);printf("    ¡ö      ");
		i+=12;break;
	case 'z':j=jj*8;
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("            ");
		gotoxy(i,j++);printf("  ¡ö¡ö¡ö¡ö  ");
		gotoxy(i,j++);printf("      ¡ö    ");
		gotoxy(i,j++);printf("    ¡ö      ");
		gotoxy(i,j++);printf("  ¡ö¡ö¡ö¡ö  ");
		i+=12;break;
	default: break;
	}
}
}